name: Proof HTMLLLL

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 90 seconds
        run: sleep 90

      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
